# Jekyll Resume Theme

# Site settings
title: C.W. Park CV
email: ironbear12@kaist.ac.kr
description: CV of Chulwoong Park
baseurl: ""
url: "http://cwoong2park.github.io"
name: Chulwoong Park
job: Master Candidate
school: KAIST
lab: Urban Design Lab
location: Daejeon, South Korea
languages: Python, HTML
github_username:  cwoong2park
email_address: ironbear12@kaist.ac.kr

# Build settings
markdown: kramdown
